name: Backend CI (Express)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: |
          npm install

  lint:
    runs-on: windows-latest
    needs: install_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'

      - name: Lint code
        run: |
          npm run lint
